# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='Need desc', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='createdOn',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
